class Reports::Tickets::GrossExport::SicPresenter < Reports::Tickets::GrossExport::BasePresenter

  COLUMNS = [
    :organ,
    :subnet,
    :departments,
    :departments_classification,
    :subdepartment,
    :protocol,
    :created_by,
    :description,
    :shared,
    :other_organs,
    :internal_status,
    :topic,
    :subtopic,
    :budget_program,
    :service_type,
    :origem_input,
    :year,
    :month,
    :confirmed_at,
    :answered_at,
    :final_answer_at,
    :answer_time_in_days,
    :immediate_answer,
    :last_answer_status,
    :last_answer_status_department,
    :answers_description,
    :answers_department_created_at,
    :reopened,
    :reopened_description,
    :appeals,
    :neighborhood,
    :city,
    :state,
    :answer_type,
    :deadline,
    :evaluation,
    :has_extension,
    :answer_classification,
    :attendance_evaluation,
    :average_attendance_evaluation_organ
  ] + COLUMNS_CREATOR_INFO
end
