#
# Rake para popular a lista de rede de ouvidoria do tipo executivo.
#
# É do tipo 'create_or_update' (chave: title) pois não destrói dados.
#

namespace :ombudsmen do
  namespace :executive do
    task create_or_update: :environment do

      ombudsmen = [
        {
          title: 'Agência de Defesa Agropecuária do Estado do Ceará - ADAGRI',
          contact_name: 'Luciana Freire Castelo Branco',
          phone: '(85) 3433-4893',
          email: 'luciana.castelobranco@adagri.ce.gov.br',
          address: 'Av. Bezerra de Menezes, nº 1820, São Gerardo - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Agência de Desenvolvimento do Estado do Ceará - ADECE',
          contact_name: 'Maria Cecy de Castro ',
          phone: '(85) 3457-3343',
          email: 'cecy@adece.ce.gov.br',
          address: 'Av. Dom Luís, nº 807 - Ed. Etevaldo Nogueira (7º Andar), Meireles - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Academia Estadual de Segurança Pública do Ceará - AESP/CE',
          contact_name: 'Fernanda Patrícia Cavalcante de Melo',
          phone: '(85) 3296-4206',
          email: 'ouvidoria@aesp.ce.gov.br',
          address: 'Avenida Presidente Costa e Silva, 1251, Mondubim – Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Agência Reguladora de Serviços Públicos Delegados do Estado do Ceará - ARCE/CE',
          contact_name: 'Daniela Carvalho Cambraia Dantas',
          phone: '(85) 3101-1024',
          email: 'ouvidor@arce.ce.gov.br',
          address: 'Av. Santos Dumont, nº 1789 (14º Andar), Aldeota - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Companhia de Água e Esgoto do Ceará - CAGECE',
          contact_name: 'Jamile Maia Braide',
          phone: '(85) 3101-1783',
          email: 'jamile.braide@cagece.com.br',
          address: 'Av. Dr. Lauro Vieira Chaves, nº1030, Vila União - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Casa Civil',
          contact_name: 'Joaquim Alexandrino Feitosa Gonçalves',
          phone: '(85) 3466-4927',
          email: 'joaquim.feitosa@casacivil.ce.gov.br',
          address: 'Av. Barão de Studart, nº 505, Palácio da Abolição, Meireles - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Corpo de Bombeiros Militar do Estado do Ceará - CBMCE',
          contact_name: 'Major Haroldo Jorge Aragão Gondim',
          phone: '(85) 3101-2217',
          email: 'ouvidor@cb.ce.gov.br, haroldo.gondim@cb.ce.gov.br ',
          address: 'Rua Oto de Alencar, 215, Jacarecanga - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Companhia de Integração Portuária do Ceará - CEARÁ PORTOS',
          contact_name: 'Ernesto de Oliveira Aderaldo Neto',
          phone: '(85) 3372-1516',
          email: 'ouvidoria@cearaportos.ce.gov.br',
          address: 'Esplanada do Pecém, s/nº,  Pecém - São Gonçalo do Amarante/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Centrais de Abastecimento do Ceará S/A - CEASA',
          contact_name: 'Cláudia Trindade Corrêa Lopes ',
          phone: '(85) 3299-1259',
          email: 'controladoria@ceasa-ce.com.br',
          address: 'Av. Dr. Mendel Steinbruch, S/N, Pajuçara - Maracanaú/CE',
          operating_hours: '8h às 13h',
        },
        {
          title: 'Conselho Estadual de Educação - CEE',
          contact_name: 'Maria Cláudia Leite Coêlho',
          phone: '(88) 3272-3044',
          email: 'claudia.coelho@cee.ce.gov.br',
          address: 'Rua Napoleão Laureano, 500, Bairro de Fátima – Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Centro de Educação à Distância - CED',
          contact_name: 'Dayelle Kelly Coelho Rodrigues',
          phone: '(88) 3695-1950 88) 3695-1951',
          email: 'dayelle.kelly@ced.seduc.ce.gov.br',
          address: 'Rua Dona Iolanda Barreto, 317, Bairro Derby - Sobral/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Companhia de Gás do Ceará - CEGÁS',
          contact_name: 'Paulo Sérgio Souto Mota',
          phone: '(85) 3266-6924',
          email: 'paulo.mota@cegas.com.br',
          address: 'Av. Washington Soares, 55, Ed. Empresarial Iguatemi (11º andar), Bairro Cocó - Fortaleza-CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Controladoria Geral de Disciplina dos Órgãos de Segurança Pública e Sistema Penitenciário -  CGD',
          contact_name: 'Major Moyses Loiola Weyne',
          phone: '(85) 3254-3495',
          email: 'moyses.weyne@cgd.ce.gov.br',
          address: 'Av. Pessoa Anta, 69, Praia de Iracema - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Controladoria e ouvidoria Geral do Estado - CGE',
          contact_name: 'Maria Ivanilza Fernandes de Castro',
          phone: '(85) 3101-3478',
          email: 'ouvidoria.geral@cge.ce.gov.br',
          address: 'Av. Gal Afonso Albuquerque Lima, Ed. Seplag (2º Andar), Cambeba - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Companhia de Desenvolvimento do Ceará - CODECE',
          contact_name: 'Andréa de Castro Perdigão',
          phone: '(85) 3101-3413',
          email: 'andrea.perdigao@codece.ce.gov.br',
          address: 'Av. Oliveira Paiva 941, Cidade dos Funcionários - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Companhia de Gestão dos Recursos Hídricos do Ceará - COGERH',
          contact_name: 'Virgílio César Aires de Freitas',
          phone: '(85) 3195-0746',
          email: 'virgilio.aires@cogerh.com.br',
          address: 'Rua Adualdo Batista, nº 1550, Parque Iracema - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Departamento de Arquitetura e Engenharia - DAE',
          contact_name: 'Francisco Alves de Aguiar',
          phone: '(85) 3487-8844',
          email: 'ouvidoria@dae.ce.gov.br',
          address: 'Av. Alberto Craveiro, nº 2775 / Térreo, Castelão - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Departamento Estadual de Rodovias - DER',
          contact_name: 'Adília Maria Rocha Monteiro',
          phone: '(85) 3101-5714',
          email: 'ouvidoria@der.ce.gov.br',
          address: 'Av. Godofredo Maciel, nº 3000, Maraponga - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Departamento Estadual de Trânsito - DETRAN',
          contact_name: 'José de Ribamar Diniz Bacelar',
          phone: '(85) 3101-5819',
          email: 'ouvidoria@detran.ce.gov.br',
          address: 'Av. Godofredo Maciel, nº 2900, Maraponga, Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Escola de Gestão Pública do Estado do Ceará - EGP',
          contact_name: 'Juliana Lima de Almeida Menezes',
          phone: '(85) 3488-8432',
          email: 'juliana.menezes@egp.ce.gov.br',
          address: 'Av. General Afonso Albuquerque de Lima, Cambeba - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Empresa de Assistência Técnica e Extensão Rural do Ceará - EMATERCE',
          contact_name: 'Marcos Antônio Paulino Dias',
          phone: '(85) 3217-7872',
          email: 'marcos.dias@ematerce.ce.gov.br',
          address: 'Av. Bezerra de Menezes, nº 1900, São Gerardo - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Escola de Saúde Pública - ESP',
          contact_name: 'Dellane Emanuelle Pinheiro Gadelha Damasceno',
          phone: '(85) 3101-1428',
          email: 'emanuelle.damasceno@esp.ce.gov.br',
          address: 'Av. Antonio Justa, nº 3161, Meireles - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Empresa de Tecnologia da Informação do Ceará - ETICE',
          contact_name: 'Francisco Agnaldo Nogueira Lima',
          phone: '(85) 3101-6644',
          email: 'agnaldo.lima@etice.ce.gov.br',
          address: 'Av. Pontes Vieira, nº 220, São João do Tauape - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Fundação Cearense de Apoio ao Desenvolvimento Científico e Tecnológico - FUNCAP',
          contact_name: 'Marília Rêgo Gonçalves Matos',
          phone: '(85) 3275-5049',
          email: 'marilia.matos@funcap.ce.gov.br',
          address: 'Av. Oliveira Paiva nº 941, Cidade dos Funcionários - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Fundação Cearense de Meteorologia e Recursos Hídricos - FUNCEME',
          contact_name: 'Ana Célia Cristino Belchior Martins',
          phone: '(85) 3101-1098',
          email: 'ouvidoria@funceme.br; anacelia@funceme.br',
          address: 'Avenida Rui Barbosa,nº 1246, Aldeota - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Fundação de Teleducação do Ceará - FUNTELC',
          contact_name: 'Apolônia Gomes Lemos',
          phone: '(85) 3101.3110',
          email: 'opresidencia@tvceara.ce.gov.br',
          address: 'Rua Osvaldo Cruz,nº 1985, Aldeota - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Gabinete do Governador - GABGOV',
          contact_name: 'Camila Moreira Rocha Rios',
          phone: '(85) 3466-4939',
          email: 'camila.rios@gabgov.ce.gov.br',
          address: 'Av. Barão de Studart, nº 505, Palácio da Abolição, Meireles - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Gabinete do Vice-Governador - GABVICE',
          contact_name: 'Fernanda Pinto Pacheco França',
          phone: '(85) 3108-0921',
          email: 'fernanda.pacheco@vicegov.ce.gov.br',
          address: 'Av. Dr. José Martins Rodrigues, 150, Edson Queiroz - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Instituto de Desenvolvimento Agrário do Ceará - IDACE',
          contact_name: 'Augusto Clementino Rêgo Brandão',
          phone: '(85) 3101-2473',
          email: 'augusto.brandao@idace.ce.gov.br',
          address: 'Rua Pedro de Queirós, nº 87, Parquelândia – Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Instituto de Pesquisa e Estratégia Econômica do Ceara - IPECE',
          contact_name: 'Rafaela Martins Leite Monteiro',
          phone: '(85) 3101-3513',
          email: 'rafaela.martins@ipece.ce.gov.br',
          address: 'Av. General Afonso Albuquerque Lima, S/N, Cambeba - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Instituto de Saúde dos Servidores do Estado do Ceará - ISSEC',
          contact_name: 'Maria do Socorro Rufina Areal',
          phone: '(85) 3101-4818',
          email: 'ouvidoria@issec.ce.gov.br',
          address: 'Rua Senador Pompeu, nº 685, Centro - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Junta Comercial do Estado do Ceará - JUCEC',
          contact_name: 'Sonara Capaverde',
          phone: '(85) 3101-6959',
          email: 'sonara.capaverde@jucec.ce.gov.br',
          address: 'Rua 25 de Março, nº 300, Centro - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Companhia Cearense de Transportes Metropolitanos - METROFOR',
          contact_name: 'Maria Isomar da Silva Xenofonte ',
          phone: '(85) 3101-7106',
          email: 'isomar.silva@metrofor.ce.gov.br',
          address: 'Rua 24 de maio, nº 60, Centro - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Fundação Núcleo de Tecnologia Industrial do Ceará - NUTEC',
          contact_name: 'Maria Cleine de Oliveira Pinto',
          phone: '(85) 3101-2896',
          email: 'cleine.oliveira@nutec.ce.gov.br',
          address: 'Rua Prof. Rômulo Proença s/nº, Pici - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Polícia Civil - PC',
          contact_name: 'Geraldo Wilson Monteiro Nóbrega',
          phone: '(85) 3101-7354',
          email: 'ouvidoria@policiacivil.ce.gov.br',
          address: 'Rua do Rosário, nº 199, Centro - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Perícia Forense do Estado do Ceará - PEFOCE',
          contact_name: 'Danielli Rodrigues Bezerra ',
          phone: '(85) 3218-8906',
          email: 'ouvidoria@pefoce.ce.gov.br',
          address: 'Av Leste Oeste, nº 900, Pirambú - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Procuradoria Geral do Estado - PGE',
          contact_name: 'Maria Brás Paula (Aparecida)',
          phone: '(85) 3459-6351',
          email: 'ouvidoria@pge.ce.gov.br',
          address: 'Rua Doutor José Martins Rodrigues, nº 150, Edson Queiroz - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Polícia Militar - PMCE',
          contact_name: 'Cel. Magnólia de Lacerda Carvalho',
          phone: '(85) 3101-1737',
          email: 'magnolia.carvalho@pm.ce.gov.br; ouvidoria.pmce@gmail.com',
          address: 'Av. Aguanambí, nº 2280, Bairro de Fátima - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria das Cidades - SCIDADES',
          contact_name: 'Adriana Xavier de Santiago ',
          phone: '(85) 3207-5262',
          email: 'adriana.santiago@cidades.ce.gov.br',
          address: 'Av. Gal Afonso Albuquerque Lima, Ed. Seplag (1ºAndar), Cambeba - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria do Desenvolvimento Agrário - SDA',
          contact_name: 'Francisco das Chagas de Vasconcelos Araujo',
          phone: '(85) 3101-8144',
          email: 'francisco.vasconcelos@sda.ce.gov.br',
          address: 'Av. Bezerra de Menezes, nº 1820, São Gerardo - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Ciência, Tecnologia e Educação Superior - SECITECE',
          contact_name: 'Luiz Eduardo Maia Gadelha ',
          phone: '(85) 3101-6443',
          email: 'ouvidoria@sct.ce.gov.br; eduardo.gadelha@sct.ce.gov.br',
          address: 'Av. Dr. José Martins Rodrigues, nº 150, Edson Queiroz - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Educação - SEDUC',
          contact_name: 'Iranir Rodrigues Loiola',
          phone: '(85) 3101-3911',
          email: 'ouvidoria@seduc.ce.gov.br',
          address: 'Av. Gal. Albuquerque Lima, s/n, Cambeba - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Cultura - SECULT',
          contact_name: 'Raimunda Félix de Oliveira',
          phone: '(85) 3101-6780',
          email: 'ouvidoria@secult.ce.gov.br',
          address: 'Rua Major Facundo, nº 500 (8º andar, Sala 804), Centro - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Fazenda - SEFAZ',
          contact_name: 'Marcia Morais Ximenes Mendes',
          phone: '(85) 3101-9385',
          email: 'ouvidoria@sefaz.ce.gov.br',
          address: 'Av. Pessoa Anta, nº 274, Centro - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Infraestrutura - SEINFRA',
          contact_name: 'Maria Cleide Costa Maia',
          phone: '(85) 3216-3708',
          email: 'cleide.maia@seinfra.ce.gov.br',
          address: 'Av. Gen. Afonso Albuquerque Lima, s/n, Ed. Seinfra SRH, Cambeba - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Justiça e Cidadania - SEJUS',
          contact_name: 'Débora Gonçalves Lages Rebêlo',
          phone: '(85) 3231-3485',
          email: 'debora.rebelo@sejus.ce.gov.br',
          address: 'Rua Tenente Benévolo, nº 1055, Meireles - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria Estadual do Meio Ambiente - SEMA',
          contact_name: 'Marconi Alves de Sousa',
          phone: '(85) 3101-1235',
          email: 'marconi.alves@sema.ce.gov.br',
          address: 'Rua Osvaldo Cruz,nº 2366, Dionísio Torres - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Superintendência Estadual do Meio Ambiente - SEMACE',
          contact_name: 'Lene Simone de Queiroz Malveira Peixoto',
          phone: '(85) 3101-5520',
          email: 'lene.peixoto@semace.ce.gov.br',
          address: 'Rua Jaime Benévolo, nº 1400, Bairro de Fátima - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Superintendência do Sistema Estadual de Atendimento Socioeducativo - SEAS',
          contact_name: 'Carlos Eduardo Nunes de Sena',
          phone: '3216.3716',
          email: 'eduardo.sena@seas.ce.gov.br',
          address: 'Av. Oliveira Paiva, nº 941-A - Cidade dos Funcionários, Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria do Planejamento e Gestão - SEPLAG',
          contact_name: 'Notlin de Araújo Almeida ',
          phone: '(85) 3101-3866',
          email: 'notlin.araujo@seplag.ce.gov.br',
          address: 'Av. Gal Afonso Albuquerque Lima - Ed. Seplag (Térreo), Cambeba - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Saúde -  SESA',
          contact_name: 'Maria de Fátima Aguiar Lustosa  ',
          phone: '(85) 3101-5227',
          email: 'ouvidoriasesa@saude.ce.gov.br; fatima.lustosa@saude.ce.gov.br',
          address: 'Av. Almirante Barroso, nº 600, Praia de Iracema - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria do Esporte - SESPORTE',
          contact_name: 'Jorge Sergio Carneiro Redes  ',
          phone: '(85) 3101-4409',
          email: 'ouvidoria@esporte.ce.gov.br',
          address: 'Av. Alberto Craveiro, nº 2775, Estádio Plácido Castelo Branco, Castelão -Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria do Turismo - SETUR',
          contact_name: 'Maria do Socorro Araújo Câmara  ',
          phone: '(85) 3195-0221',
          email: 'socorro.camara@setur.ce.gov.br',
          address: 'Av. Washington Soares, 999, Centro de Eventos do Ceará, Pavilhão Leste, 2º mezanino, Edson Queiroz - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Superintendência de Obras Hidráulicas - SOHIDRA',
          contact_name: 'José da Silva  Pinheiro',
          phone: '(85) 3101-4723',
          email: 'jose.pinheiro@sohidra.ce.gov.br',
          address: 'Rua Adualdo Batista, nº1550, Parque Iracema - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Agricultura, Pesca e Aquicultura - SEAPA',
          contact_name: 'Yngra Lima Santos',
          phone: '(85) 3258-2850',
          email: 'ouvidoria@spa.ce.gov.br',
          address: 'Av. José Martins Rodrigues, nº 150, Edson Queiroz - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria dos Recursos Hídricos - SRH',
          contact_name: 'Goretti de Fátima Ximenes Nogueira',
          phone: '(85) 3101-4056',
          email: 'goretti.ximenes@srh.ce.gov.br',
          address: 'Av. General Afonso Albuquerque Lima, S/N, Ed. Seinfra/SRH, Cambeba -Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria da Segurança Pública e Defesa Social - SSPDS',
          contact_name: 'Ivinna Nunes de Sousa',
          phone: '(85) 3101-6543',
          email: 'ouvidoria@sspds.ce.gov.br',
          address: 'Av. Bezerra de Menezes, nº 581, São Gerardo - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria do Trabalho e Desenvolvimento Social - STDS',
          contact_name: 'Paulo Henrique Araujo Lima',
          phone: '(85) 3101-6727',
          email: 'ouvidoria@stds.ce.gov.br',
          address: 'Av. Soriano Albuquerque, 230, Joaquim Távora - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria Especial de Políticas sobre Drogas - SPD',
          contact_name: 'Elen Cristine Lavor Cordeiro',
          phone: '3238.6877',
          email: 'ouvidoria@spd.ce.gov.br',
          address: 'Rua Oto de Alencar, nº 193, Jacarecanga - Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Secretaria do Desenvolvimento Econômico - SDE',
          contact_name: 'Sueli Mota Lima Gonçalves',
          phone: '(85) 3444-2909',
          email: 'sueli.mota@cede.ce.gov.br',
          address: 'Av. Dom Luís, nº 807,  Ed. Etevaldo Nogueira (16º Andar), Meireles -  Fortaleza/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Fundação Universidade Regional do Cariri - URCA',
          contact_name: 'José Micaelson Lacerda Morais',
          phone: '(88) 3102-1218',
          email: 'ouvidoria_urca@hotmail.com e micaelson_lacerda@yahoo.com.br',
          address: 'Rua Cel. Antônio Luis, nº 1161, Pimenta - Crato/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Fundação Universidade Estadual Vale do Acaraú - UVA',
          contact_name: 'Ebe Pimentel Gomes Luz',
          phone: '(88) 3611-6661',
          email: 'ouvidoria@uvanet.br',
          address: 'Av. da Universidade, nº 850, Campus da Betânia - Sobral/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Fundação Universidade Estadual do Ceará - UECE',
          contact_name: 'Maria Zeudimar Pinheiro',
          phone: '(85) 3101-9668',
          email: 'ouvidoria.geral@uece.br ',
          address: 'Av. Dr. Silas Munguba, 1700, Campus do Itaperi - Fortaleza-CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Companhia Administradora da Zona de Processamento de Exportação do Ceará - ZPE',
          contact_name: 'Ademar Eugênio Cerqueira Lopes Filho',
          phone: '3195-2540',
          email: 'ademar.filho@zpeceara.ce.gov.br',
          address: 'Esplanada do Pecém s/n, Rodovia CE - 155, São Gonçalo do Amarante/CE',
          operating_hours: '8h às 12h e das 13h às 17h',
        },
        {
          title: 'Ouvidoria Especial dos Direitos Humanos - OEDH',
          contact_name: 'Francisco Cláudio Oliveira Silva Filho',
          phone: '3101-2998',
          email: 'ademar.filho@zpeceara.ce.gov.br',
          address: 'Rua Pedro II S/N – Antiga estação da Parangaba',
          operating_hours: '8h às 12h e das 13h às 17h',
        }
      ]

      ombudsmen.each do |item|
        ombudsman = ExecutiveOmbudsman.find_or_initialize_by(title: item[:title])
        ombudsman.attributes = item

        ombudsman.save
      end
    end
  end
end
